version: 1.0.{build}
clone_depth: 2
install:
  - ruby --version
  - gem update --system --no-ri --no-rdoc
  - gem install rufus-scheduler --no-document
build_script:
  - git submodule update --init --recursive
  - .\premake\premake5 vs2013
  - MSBuild .\Build\windows\vs2013\nanomsg_example.sln
  - ruby demo.rb